_format_version: "2.1"

services:
  - name: kong-apigateway
    url: http://127.0.0.1:3000
    routes:
      - name: rails-app
        paths:
          - /echo
        strip_path: true

plugins:
- name: cors
  service: kong-apigateway
  config:
    origins:
    - "*"
    methods:
    - GET
    - POST
    headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
    exposed_headers:
    - X-Auth-Token
    credentials: true
    max_age: 3600

- name: rate-limiting
  service: kong-apigateway
  config:
    second: 5
    policy: redis
    redis_host: 127.0.0.1
    redis_port: 6379

- name: ip-restriction
  service: kong-apigateway
  config:
    allow:
    - 127.0.0.1
